# Base
text8: &text8
   dataset: text8
   data: ../data/text8/

train: &train
   <<: *text8
   cuda: true
   n_layer: 0
   d_model: 512
   n_head: 8
   d_head: 64
   d_inner: 2048
   dropout: 0.4
   dropatt: 0.4
   optim: adam
   lr: 0.00025
   warmup_step: 12000
   max_step: 200000
   tgt_len: 2048
   mem_len: 0
   eval_tgt_len: 2048
   batch_size: 8
   multi_gpu: ddp
   log_interval: 100
   eval_interval: 5000
   text_generation_interval: 25000
   batch_chunk: 2
   pre_lnorm: true
   funnel_config: "[4, (12, 1), 4]"
   funnel_resample: custom
   boundary_ids: '["_"]'
   eval_gt_boundaries: false
   corruption_probs: [0.0, 0.0, 0.0]
   mask_type: boundary_ids
   activation_function: gelu

default:
   train:
      <<: *train
